name: ThaiRoStats-Core
version: '0.1.0-SNAPSHOT'
main: org.rostats.ROStatsPlugin
api-version: '1.21'
commands:
  status:
    description: Open player status menu
    usage: /status
    aliases: [st, char]
  roadmin:
    description: Admin commands for ROStats
    usage: /roadmin <args>
    permission: rostats.admin
permissions:
  rostats.admin:
    description: Admin permission
    default: op